### ISSUE TITLE
luamin fails to change goto labels resulting in unrunnable code

### ISSUE THREAD

**Issue by macsimilian** [dansanderson/picotool#56] opened 2018-10-21 19:39 UTC
![pluswave_after_fmt_000](https://user-images.githubusercontent.com/5558680/47271447-84ab1900-d547-11e8-9d65-917cf2916731.png)

**Comment by macsimilian** [comment] 2018-10-21 20:58
all 3 goto labels in this cart were renamed, but their corresponding goto commands weren't

**Comment by dansanderson** [comment] 2021-08-30 08:08
@macsimilian Apologies that this issue is very old. Do you still have the example that breaks this? Can you attach the cart, or paste the code, into this issue?

The intended behavior is for both the label and the goto symbol to be treated like any other symbol and appropriately renamed. Simple tests show that both the goto and the label are getting minified.

**Comment by macsimilian** [comment] 2021-09-06 00:18
This is the cart that it was broken for, not sure if the exact version though. I ended up compressing space by going through and removing all the indentations.

![pluswave p8](https://user-images.githubusercontent.com/5558680/132145431-8039a7e9-2adf-40c2-b178-363f699d5c8c.png)

**Comment by Liquidream** [comment] 2021-09-06 05:31
Just remembered that I too still seem to have experienced this issue.
I had to add all labels to "keep" list in order to avoid error.

**Comment by dansanderson** [comment] 2021-09-10 07:38
This is now fixed. luamin will minify labels correctly, no need to add them to the keep list. abce6967a89f055c4df602995180b45392a5b27f

Also high chars are now supported in labels (and symbols).

**Closed by dansanderson** 2021-09-10 07:38 UTC
